// version profesional v2.2 ducks - admin CRUD + WhatsApp atrasados + logo HD
const app=document.getElementById('app');let sb=null,session=null,page='portal',players=[],payments=[],q='';
const $=id=>document.getElementById(id);function toast(m){const t=$('toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2400)}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}function money(n){return Number(n||0).toLocaleString('es-MX',{style:'currency',currency:'MXN'})}function todayISO(){return new Date().toISOString().slice(0,10)}function period(d){return String(d||'').slice(0,7)}function statusClass(s){return String(s||'').replace(/\s+/g,'')}function thumb(u){return u?`<div class="thumb"><img src="${u}"></div>`:`<div class="thumb"><div class="emptythumb">Sin foto</div></div>`}function configured(){return window.DUCKS_SUPABASE_URL&&!window.DUCKS_SUPABASE_URL.includes('TU-PROYECTO')&&window.DUCKS_SUPABASE_ANON_KEY&&!window.DUCKS_SUPABASE_ANON_KEY.includes('TU_ANON')}function nextId(){const m=players.reduce((a,p)=>Math.max(a,Number(String(p.id||'').replace(/\D/g,''))||0),0);return'D'+String(m+1).padStart(3,'0')}function normPhone(v){const d=String(v||'').replace(/\D/g,'');if(!d)return'';if(d.startsWith('52')&&d.length===12)return'+'+d;if(d.length===10)return'+52'+d;if(d.length>=11&&d.length<=15)return'+'+d;return String(v||'').trim()}
function calc(p){const c=payments.filter(x=>x.player_id===p.id&&x.confirmation_status==='Confirmado').sort((a,b)=>String(b.payment_date).localeCompare(String(a.payment_date)));const last=c[0]?.payment_date||'';const now=new Date(),ld=last?new Date(last+'T00:00:00'):null,active=String(p.status||'').toLowerCase()==='activo';let months=0;if(active)months=!ld?1:Math.max(0,(now.getFullYear()-ld.getFullYear())*12+(now.getMonth()-ld.getMonth()));const amount=active?months*Number(p.monthly_fee||0):0;let status='Inactivo';if(active){if(months===0)status='Pagado';else if(months===1&&now.getDate()<=Number(p.payment_day||1))status='Pendiente';else status='Vencido'}return{last,months,amount,status}}
async function init(){if(!configured()){app.innerHTML='<div class="panel" style="max-width:760px;margin:60px auto"><div class="panel-head"><h3>Configurar Supabase</h3></div><div class="modal-body"><div class="notice warning">Falta configurar config.js.</div></div></div>';return}sb=window.supabase.createClient(window.DUCKS_SUPABASE_URL,window.DUCKS_SUPABASE_ANON_KEY);const{data}=await sb.auth.getSession();session=data.session;renderShell();if(session)await loadAdmin();else await loadPublic();renderPage()}
async function loadPublic(){const{data,error}=await sb.from('public_players').select('*').order('name');if(error){toast('Error cargando jugadores: '+error.message);return}players=data||[];payments=[]}async function loadAdmin(){const pr=await sb.from('players').select('*').order('id');if(pr.error){toast('Error jugadores: '+pr.error.message);return}players=pr.data||[];const py=await sb.from('payments').select('*').order('created_at',{ascending:false});if(py.error){toast('Error pagos: '+py.error.message);return}payments=py.data||[]}async function refresh(){if(session)await loadAdmin();else await loadPublic();renderPage()}
function renderShell(){app.innerHTML=`<div class="shell"><aside class="side"><div class="brand"><img class="brand-logo" src="assets/logo.png"><div><h1>Ducks Academy CRM</h1><p>Portal de pagos y administración</p></div></div><div class="nav"><button data-page="portal">👨‍👩‍👧 Portal papás</button><button data-page="dashboard">📊 Dashboard</button><button data-page="players">🏀 Jugadores</button><button data-page="payments">💳 Pagos</button><button data-page="evidence">📎 Evidencias</button><button data-page="settings">⚙️ Configuración</button></div><div class="help">v2.2: portal profesional + administración completa + WhatsApp para pagos atrasados.</div></aside><main class="main"><div class="top"><div><h2 id="title"></h2><p>Ducks Basketball Academy</p></div><div class="tools"><input id="search" class="input" placeholder="Buscar..." value="${esc(q)}"><button class="btn secondary" id="authBtn"></button></div></div><div id="content"></div></main></div>`;document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{page=b.dataset.page;renderPage()});$('search').oninput=e=>{q=e.target.value;renderPage()};$('authBtn').onclick=()=>session?logout():renderLogin()}
function setTitle(t){$('title').textContent=t;document.querySelectorAll('[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===page));$('authBtn').textContent=session?'Cerrar sesión':'Admin login'}function needAdmin(){if(!session){renderLogin();return false}return true}function renderPage(){if(page==='portal'){renderPortal();return}if(page==='settings'){session?renderSettings():renderLogin();return}if(!needAdmin())return;if(page==='dashboard')renderDashboard();if(page==='players')renderPlayers();if(page==='payments')renderPayments();if(page==='evidence')renderEvidence()}
function filtered(){const s=q.toLowerCase().trim();return players.filter(p=>!s||[p.id,p.name,p.tutor,p.phone,p.category,p.uniform_number].join(' ').toLowerCase().includes(s))}
function renderDashboard(){setTitle('Dashboard ejecutivo');const rows=players.map(p=>({...p,c:calc(p)})),active=rows.filter(p=>p.status==='Activo').length,debt=rows.filter(p=>p.c.amount>0),over=rows.filter(p=>p.c.status==='Vencido').length,pend=payments.filter(p=>p.confirmation_status==='Pendiente de confirmación').length,total=debt.reduce((a,p)=>a+p.c.amount,0);$('content').innerHTML=`<div class="kpis"><div class="kpi"><small>Jugadores</small><strong>${players.length}</strong></div><div class="kpi green"><small>Activos</small><strong>${active}</strong></div><div class="kpi orange"><small>Con adeudo</small><strong>${debt.length}</strong></div><div class="kpi red"><small>Vencidos</small><strong>${over}</strong></div><div class="kpi orange"><small>Por confirmar</small><strong>${pend}</strong></div><div class="kpi red"><small>Adeudo total</small><strong>${money(total)}</strong></div></div><div class="panel"><div class="panel-head"><h3>Jugadores con adeudo</h3></div><div class="tablewrap"><table><thead><tr><th>Foto</th><th>ID</th><th>Jugador</th><th>Núm.</th><th>Tutor</th><th>Último pago</th><th>Meses</th><th>Adeudo</th><th>Estado</th></tr></thead><tbody>${debt.sort((a,b)=>b.c.amount-a.c.amount).map(p=>`<tr><td>${thumb(p.photo_url)}</td><td>${p.id}</td><td><b>${esc(p.name)}</b><br><small>${esc(p.category||'')}</small></td><td><span class="uniform">#${esc(p.uniform_number||'-')}</span></td><td>${esc(p.tutor||'')}</td><td>${esc(p.c.last||'')}</td><td>${p.c.months}</td><td class="amount">${money(p.c.amount)}</td><td><span class="status ${p.c.status}">${p.c.status}</span></td></tr>`).join('')||'<tr><td colspan="9">Sin adeudos</td></tr>'}</tbody></table></div></div>`}
function renderPlayers(){setTitle('Jugadores');const list=filtered();$('content').innerHTML=`<div class="panel"><div class="panel-head"><h3>Base de jugadores</h3><button class="btn green" onclick="openPlayerForm()">+ Nuevo jugador</button></div><div class="cards">${list.map(p=>`<div class="card">${thumb(p.photo_url)}<h4>${esc(p.name)}</h4><p><span class="uniform">#${esc(p.uniform_number||'-')}</span></p><p><b>ID:</b> ${p.id} · <b>Categoría:</b> ${esc(p.category||'')}</p><p><b>Tutor:</b> ${esc(p.tutor||'')}</p><p><b>WhatsApp:</b> ${esc(p.phone||'')}</p><p><b>Mensualidad:</b> ${money(p.monthly_fee)} · Día ${p.payment_day}</p><div class="actions"><button class="btn secondary" onclick="openPlayerForm('${p.id}')">Editar</button><button class="btn green" onclick="openPaymentForm('${p.id}')">Pago</button><button class="btn red" onclick="deletePlayer('${p.id}')">Eliminar</button></div></div>`).join('')||'<div class="card">Sin jugadores</div>'}</div></div>`}
function renderPayments(){setTitle('Pagos');$('content').innerHTML=`<div class="panel"><div class="panel-head"><h3>Historial de pagos</h3><button class="btn green" onclick="openPaymentForm()">+ Registrar pago</button></div><div class="tablewrap"><table><thead><tr><th>ID</th><th>Alumno</th><th>Fecha</th><th>Periodo</th><th>Monto</th><th>Método</th><th>Estatus</th><th>Evidencia</th><th>Acción</th></tr></thead><tbody>${payments.map(p=>`<tr><td>${String(p.id).slice(0,8)}</td><td><b>${esc(p.student_name||'')}</b><br><small>${esc(p.player_id)}</small></td><td>${esc(p.payment_date)}</td><td>${esc(p.period||'')}</td><td class="amount">${money(p.amount)}</td><td>${esc(p.method||'')}</td><td><span class="status ${statusClass(p.confirmation_status)}">${esc(p.confirmation_status)}</span></td><td>${p.evidence_url?`<a class="btn secondary" target="_blank" href="${p.evidence_url}">Ver</a>`:'-'}</td><td><button class="btn red" onclick="deletePayment('${p.id}')">Eliminar</button></td></tr>`).join('')||'<tr><td colspan="9">Sin pagos</td></tr>'}</tbody></table></div></div>`}
function renderEvidence(){setTitle('Evidencias por confirmar');const pend=payments.filter(p=>p.confirmation_status==='Pendiente de confirmación');$('content').innerHTML=`<div class="notice warning">Al confirmar un pago, se reflejará automáticamente en el dashboard y adeudos.</div><div class="panel"><div class="panel-head"><h3>Pendientes</h3></div><div class="tablewrap"><table><thead><tr><th>Alumno</th><th>Fecha</th><th>Periodo</th><th>Monto</th><th>Enviado por</th><th>Evidencia</th><th>Acción</th></tr></thead><tbody>${pend.map(p=>`<tr><td><b>${esc(p.student_name)}</b><br><small>${esc(p.player_id)}</small></td><td>${p.payment_date}</td><td>${esc(p.period||'')}</td><td class="amount">${money(p.amount)}</td><td>${esc(p.submitted_by||'')}</td><td>${p.evidence_url?`<a class="btn secondary" target="_blank" href="${p.evidence_url}">Ver evidencia</a>`:'-'}</td><td><button class="btn green" onclick="confirmPayment('${p.id}')">Confirmar</button> <button class="btn red" onclick="rejectPayment('${p.id}')">Rechazar</button></td></tr>`).join('')||'<tr><td colspan="7">No hay evidencias pendientes.</td></tr>'}</tbody></table></div></div>`}
function renderPortal(){setTitle('Portal de pago para papás');$('content').innerHTML=`<div class="panel"><div class="panel-head"><h3>Enviar evidencia de pago</h3></div><div class="modal-body"><div class="portal-hero"><div><h3>Portal oficial de pagos Ducks Basketball Academy</h3><p>Registra tu pago y adjunta el comprobante. El pago quedará pendiente de confirmación administrativa.</p><p class="portal-url">${esc(window.DUCKS_PORTAL_URL||location.href)}</p></div><img src="assets/portal_qr.png" alt="QR"></div><div class="notice success"><b>Instrucciones:</b> selecciona el jugador, captura el monto pagado, adjunta la evidencia y presiona enviar.</div><form id="portalForm" class="form-grid"><label class="label full">Jugador<select id="portalPlayer" class="select" required><option value="">Selecciona...</option>${players.map(p=>`<option value="${p.id}">${p.id} · ${esc(p.name)} · #${esc(p.uniform_number||'-')}</option>`).join('')}</select></label><label class="label">Fecha de pago<input id="portalDate" class="input" type="date" required value="${todayISO()}"></label><label class="label">Periodo<input id="portalPeriod" class="input" value="${period(todayISO())}"></label><label class="label">Monto<input id="portalAmount" class="input" type="number" min="0" step="50" required></label><label class="label">Método<select id="portalMethod" class="select" required><option></option><option>Transferencia</option><option>Depósito</option><option>Efectivo</option><option>Otro</option></select></label><label class="label">Nombre de quien envía<input id="portalBy" class="input" placeholder="Papá / Mamá / Tutor"></label><label class="label full">Comprobante<input id="portalEvidence" class="input" type="file" accept="image/*,application/pdf" required></label><label class="label full">Comentarios<textarea id="portalNotes" class="input"></textarea></label><div class="full"><button class="btn green">Enviar evidencia</button></div></form></div></div>`;$('portalPlayer').onchange=()=>{const p=players.find(x=>x.id===$('portalPlayer').value);if(p)$('portalAmount').value=p.monthly_fee||0};$('portalForm').onsubmit=submitPortalPayment}

function reminderMessage(player){
  const c = calc(player);
  const monthsText = c.months > 1 ? `, correspondiente a ${c.months} meses de adeudo.` : '.';
  return `Hola, buen día. Les recordamos amablemente que está pendiente el pago de la mensualidad de Ducks Basketball Academy por ${money(c.amount)}${monthsText}\n\nPara facilitar el proceso, pueden subir su comprobante en el portal oficial:\n${window.DUCKS_PORTAL_URL || location.origin}\n\nAgradecemos mucho su apoyo para mantener el control administrativo. 🏀🦆`;
}
function whatsappUrl(player){
  const phone = String(player.phone||'').replace(/\D/g,'');
  if(!phone) return '';
  return `https://wa.me/${phone}?text=${encodeURIComponent(reminderMessage(player))}`;
}
function overduePlayers(){
  return players.map(p=>({...p,c:calc(p)}))
    .filter(p=>String(p.status||'').toLowerCase()==='activo' && p.phone && p.c.amount>0 && (p.c.status==='Vencido' || p.c.status==='Pendiente'))
    .sort((a,b)=>(a.c.status==='Vencido'?0:1)-(b.c.status==='Vencido'?0:1)||b.c.amount-a.c.amount||a.name.localeCompare(b.name));
}
function renderWhatsApp(){
  setTitle('WhatsApp atrasados');
  const rows = overduePlayers();
  const vencidos = rows.filter(p=>p.c.status==='Vencido').length;
  const pendientes = rows.filter(p=>p.c.status==='Pendiente').length;
  const total = rows.reduce((a,p)=>a+p.c.amount,0);
  document.getElementById('content').innerHTML = `<div class="notice warning"><b>Recordatorios listos:</b> el sistema detecta jugadores con pagos vencidos o pendientes, genera el mensaje y abre WhatsApp con el texto listo. El envío 100% automático sin abrir WhatsApp requiere API oficial de WhatsApp Business.</div>
  <div class="kpis">
    <div class="kpi red"><small>Vencidos</small><strong>${vencidos}</strong></div>
    <div class="kpi orange"><small>Pendientes</small><strong>${pendientes}</strong></div>
    <div class="kpi"><small>Con WhatsApp</small><strong>${rows.length}</strong></div>
    <div class="kpi red"><small>Adeudo a recordar</small><strong>${money(total)}</strong></div>
  </div>
  <div class="panel"><div class="panel-head"><div><h3>Mensajes para papás atrasados</h3><div class="sub">Usa “Abrir WhatsApp” para enviar individualmente o “Copiar mensaje”.</div></div><button class="btn secondary" onclick="copyAllReminders()">Copiar resumen</button></div>
  <div class="tablewrap"><table><thead><tr><th>ID</th><th>Jugador</th><th>Tutor</th><th>WhatsApp</th><th>Meses</th><th>Adeudo</th><th>Estado</th><th>Acción</th></tr></thead><tbody>
  ${rows.map(p=>`<tr><td>${p.id}</td><td><b>${esc(p.name)}</b><br><small>${esc(p.category||'')}</small></td><td>${esc(p.tutor||'')}</td><td>${esc(p.phone||'')}</td><td>${p.c.months}</td><td class="amount">${money(p.c.amount)}</td><td><span class="status ${p.c.status}">${p.c.status}</span></td><td><button class="btn secondary" onclick="copyReminder('${p.id}')">Copiar</button> ${whatsappUrl(p)?`<a class="btn green" target="_blank" href="${whatsappUrl(p)}">Abrir WhatsApp</a>`:''}</td></tr>`).join('')||'<tr><td colspan="8">No hay pagos atrasados con WhatsApp registrado.</td></tr>'}
  </tbody></table></div></div>`;
}
async function copyReminder(id){
  const p = players.find(x=>x.id===id);
  if(!p) return;
  await navigator.clipboard.writeText(reminderMessage(p));
  toast('Mensaje copiado');
}
async function copyAllReminders(){
  const rows = overduePlayers();
  const text = rows.map(p=>`${p.id} · ${p.name} · ${p.phone} · ${money(p.c.amount)} · ${p.c.status}`).join('\n');
  await navigator.clipboard.writeText(text);
  toast('Resumen copiado');
}

function renderSettings(){setTitle('Configuración');const url=window.DUCKS_PORTAL_URL||location.origin;const msg=`Hola, buen día. 🏀\n\nPara mejorar el control administrativo de Ducks Basketball Academy, a partir de ahora los pagos y comprobantes se registrarán en nuestro portal oficial.\n\nLiga del portal:\n${url}\n\nInstrucciones:\n1. Selecciona el nombre del jugador.\n2. Captura la fecha y monto pagado.\n3. Adjunta el comprobante de pago.\n4. Envía la evidencia para confirmación.\n\nUna vez validado, el pago se reflejará en el estado de cuenta del jugador.\n\nGracias por su apoyo y compromiso. 🦆🏀`;$('content').innerHTML=`<div class="panel"><div class="panel-head"><h3>Configuración profesional</h3></div><div class="modal-body"><p><b>Usuario:</b> ${session?.user?.email||'Sin sesión'}</p><div class="notice"><b>Link oficial para papás:</b><br><a href="${url}" target="_blank">${url}</a></div><div class="portal-kit"><img src="assets/portal_qr.png"><div><h3>QR del portal</h3><p>Comparte este QR en WhatsApp, impresos o redes sociales.</p></div></div><label class="label full">Mensaje sugerido para WhatsApp<textarea id="parentMsg" class="input" rows="10">${msg}</textarea></label><div class="tools" style="margin-top:12px"><button class="btn" onclick="navigator.clipboard.writeText($('parentMsg').value);toast('Mensaje copiado')">Copiar mensaje</button><button class="btn secondary" onclick="refresh()">Recargar datos</button><button class="btn green" onclick="goPage('whatsapp')">Ver WhatsApp atrasados</button></div></div></div>`}
function renderLogin(){page='settings';setTitle('Admin login');$('content').innerHTML=`<div class="panel"><div class="panel-head"><h3>Entrar como administrador</h3></div><div class="modal-body"><div class="notice">El portal de papás puede recibir evidencias sin login. Para administrar jugadores y confirmar pagos, inicia sesión.</div><form id="loginForm" class="form-grid"><label class="label">Email<input id="loginEmail" class="input" type="email" required></label><label class="label">Password<input id="loginPassword" class="input" type="password" required></label><div class="full"><button class="btn green">Entrar</button></div></form></div></div>`;$('loginForm').onsubmit=login}
async function login(e){e.preventDefault();const{data,error}=await sb.auth.signInWithPassword({email:$('loginEmail').value,password:$('loginPassword').value});if(error){toast(error.message);return}session=data.session;page='dashboard';renderShell();await loadAdmin();renderPage()}async function logout(){await sb.auth.signOut();session=null;page='portal';renderShell();await loadPublic();renderPage()}
async function uploadFile(file,folder){if(!file)return'';const clean=file.name.replace(/[^a-zA-Z0-9._-]/g,'_');const path=`${folder}/${Date.now()}_${clean}`;const{error}=await sb.storage.from('ducks-files').upload(path,file,{upsert:false});if(error)throw error;return sb.storage.from('ducks-files').getPublicUrl(path).data.publicUrl}
function closeModal(id){const el=$(id);if(el)el.remove()}function openPlayerForm(id=''){const p=id?players.find(x=>x.id===id):null;const m=document.createElement('div');m.className='modalbg open';m.id='playerModal';m.innerHTML=`<div class="modal"><div class="modal-head"><h3>${p?'Editar jugador':'Nuevo jugador'}</h3><button class="btn secondary" onclick="closeModal('playerModal')">Cerrar</button></div><div class="modal-body"><form id="playerForm" class="form-grid"><label class="label">ID jugador<input id="pId" class="input" value="${esc(p?.id||nextId())}" ${p?'readonly':''} required></label><label class="label">Nombre<input id="pName" class="input" value="${esc(p?.name||'')}" required></label><label class="label">Tutor<input id="pTutor" class="input" value="${esc(p?.tutor||'')}"></label><label class="label">WhatsApp<input id="pPhone" class="input" value="${esc(p?.phone||'')}"></label><label class="label">Categoría<input id="pCategory" class="input" value="${esc(p?.category||'')}"></label><label class="label">Estado<select id="pStatus" class="select"><option ${p?.status==='Activo'?'selected':''}>Activo</option><option ${p?.status==='Inactivo'?'selected':''}>Inactivo</option><option ${p?.status==='Baja'?'selected':''}>Baja</option></select></label><label class="label">Mensualidad<input id="pFee" class="input" type="number" min="0" step="50" value="${esc(p?.monthly_fee||300)}"></label><label class="label">Día de pago<input id="pDay" class="input" type="number" min="1" max="31" value="${esc(p?.payment_day||5)}"></label><label class="label">Número uniforme<input id="pUniform" class="input" value="${esc(p?.uniform_number||'')}"></label><label class="label">Foto<input id="pPhoto" class="input" type="file" accept="image/*"></label><label class="label full">Notas<textarea id="pNotes" class="input">${esc(p?.notes||'')}</textarea></label><div class="full actions"><button class="btn green">Guardar jugador</button></div></form></div></div>`;document.body.appendChild(m);$('playerForm').onsubmit=e=>savePlayerForm(e,p)}
async function savePlayerForm(e,old){e.preventDefault();try{let photo=old?.photo_url||'';const file=$('pPhoto').files[0];if(file)photo=await uploadFile(file,'fotos');const row={id:$('pId').value.trim(),name:$('pName').value.trim(),tutor:$('pTutor').value.trim(),phone:normPhone($('pPhone').value),category:$('pCategory').value.trim(),status:$('pStatus').value,monthly_fee:Number($('pFee').value||0),payment_day:Number($('pDay').value||1),uniform_number:$('pUniform').value.trim(),photo_url:photo,notes:$('pNotes').value.trim()};const res=old?await sb.from('players').update(row).eq('id',old.id):await sb.from('players').insert(row);if(res.error)throw res.error;toast(old?'Jugador actualizado':'Jugador agregado');closeModal('playerModal');await refresh()}catch(err){toast('Error: '+err.message)}}
async function deletePlayer(id){const p=players.find(x=>x.id===id);if(!p||!confirm(`¿Eliminar a ${p.name}? También se eliminarán sus pagos.`))return;const{error}=await sb.from('players').delete().eq('id',id);if(error)toast('Error: '+error.message);else{toast('Jugador eliminado');await refresh()}}
function openPaymentForm(playerId=''){const sel=players.find(p=>p.id===playerId);const m=document.createElement('div');m.className='modalbg open';m.id='paymentModal';m.innerHTML=`<div class="modal"><div class="modal-head"><h3>Registrar pago confirmado</h3><button class="btn secondary" onclick="closeModal('paymentModal')">Cerrar</button></div><div class="modal-body"><form id="paymentForm" class="form-grid"><label class="label full">Jugador<select id="payPlayer" class="select" required><option value="">Selecciona...</option>${players.map(p=>`<option value="${p.id}" ${p.id===playerId?'selected':''}>${p.id} · ${esc(p.name)}</option>`).join('')}</select></label><label class="label">Fecha<input id="payDate" class="input" type="date" value="${todayISO()}" required></label><label class="label">Periodo<input id="payPeriod" class="input" value="${period(todayISO())}"></label><label class="label">Monto<input id="payAmount" class="input" type="number" min="0" step="50" value="${esc(sel?.monthly_fee||300)}" required></label><label class="label">Método<select id="payMethod" class="select"><option></option><option>Transferencia</option><option>Depósito</option><option>Efectivo</option><option>Tarjeta</option><option>Otro</option></select></label><label class="label">Evidencia opcional<input id="payEvidence" class="input" type="file" accept="image/*,application/pdf"></label><label class="label full">Notas<textarea id="payNotes" class="input"></textarea></label><div class="full actions"><button class="btn green">Guardar pago confirmado</button></div></form></div></div>`;document.body.appendChild(m);$('payPlayer').onchange=()=>{const p=players.find(x=>x.id===$('payPlayer').value);if(p)$('payAmount').value=p.monthly_fee||0};$('paymentForm').onsubmit=savePaymentForm}
async function savePaymentForm(e){e.preventDefault();try{const id=$('payPlayer').value,p=players.find(x=>x.id===id),file=$('payEvidence').files[0],url=file?await uploadFile(file,'evidencias'):'';const row={player_id:id,student_name:p?.name||'',payment_date:$('payDate').value,period:$('payPeriod').value||period($('payDate').value),amount:Number($('payAmount').value||0),method:$('payMethod').value,notes:$('payNotes').value,confirmation_status:'Confirmado',evidence_url:url,evidence_name:file?.name||'',submitted_by:'Admin',confirmed_at:new Date().toISOString()};const{error}=await sb.from('payments').insert(row);if(error)throw error;toast('Pago guardado y confirmado');closeModal('paymentModal');page='payments';await refresh()}catch(err){toast('Error: '+err.message)}}
async function submitPortalPayment(e){e.preventDefault();try{const id=$('portalPlayer').value,p=players.find(x=>x.id===id),file=$('portalEvidence').files[0],url=await uploadFile(file,'evidencias');const row={player_id:id,student_name:p?.name||'',payment_date:$('portalDate').value,period:$('portalPeriod').value||period($('portalDate').value),amount:Number($('portalAmount').value||0),method:$('portalMethod').value,submitted_by:$('portalBy').value,notes:$('portalNotes').value,confirmation_status:'Pendiente de confirmación',evidence_url:url,evidence_name:file.name};const{error}=await sb.from('payments').insert(row);if(error)throw error;e.target.reset();toast('Evidencia enviada. Queda pendiente de confirmación.')}catch(err){toast('Error: '+err.message)}}
async function confirmPayment(id){const{error}=await sb.from('payments').update({confirmation_status:'Confirmado',confirmed_at:new Date().toISOString()}).eq('id',id);if(error)toast(error.message);else{toast('Pago confirmado');await refresh()}}async function rejectPayment(id){const{error}=await sb.from('payments').update({confirmation_status:'Rechazado'}).eq('id',id);if(error)toast(error.message);else{toast('Pago rechazado');await refresh()}}async function deletePayment(id){if(!confirm('¿Eliminar pago?'))return;const{error}=await sb.from('payments').delete().eq('id',id);if(error)toast(error.message);else{toast('Pago eliminado');await refresh()}}
Object.assign(window,{openPlayerForm,deletePlayer,openPaymentForm,confirmPayment,rejectPayment,deletePayment,refresh,closeModal});init();
